project:
  type: website
  output-dir: docs

website:
  title: "Monkey's Uncle"
  site-url: https://https://eehh-stanford.github.io/monkeys_uncle
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/juemos
      - icon: twitter
        href: https://bsky.app/profile/juemos.bsky.social
      - icon: mastodon
        href: https://fediscience.org/@juemos
format:
  html:
    theme: yeti
    css: styles.css

editor: visual

