---
title: "An Alternate Courseload for the Game of Life"
author: "James Holland Jones"
date: "2026-06-14"
categories:
  - education
  - climate change
  - economics
  - sociology
  - literature
  - biology
  - statistics
---

It's Stanford's commencement weekend and this got me to thinking about an old blog post I wrote. Here, I've managed to recover the post using the Wayback Machine and have edited it a bit here. I  originally published this 7 September 2010. As it's been 16 years (!), I also felt like I needed to add a bit of new material to bring it more up to date. 

In an [editorial](https://archive.nytimes.com/www.nytimes.com/2010/09/05/business/economy/05view.html) in the _New York Times_ back in 2010, Harvard economist and former chairman of the Council of Economic Advisers, [N. Gregory Mankiw](https://mankiw.scholars.harvard.edu/) provided some answers to the question "what kind of foundation is needed to understand and be prepared for the modern economy?" I got a bit tweaked by this piece and blogged about it in the first incarnation of Monkey's Uncle. Here, I recreate this post with updated links, etc. and a few more thoughts now that we're 16 years further on into the 21st century.

Presumably, what Mankiw meant by "modern economy" is life after college. He suggested that students of all ages learn something about the following subjects: economics, statistics, finance, and psychology (which I actually read to actually mean economics, econometrics, financial economics, and behavioral economics). Reading this editorial made me think of my own list, which is rather different than the one offered by Mankiw. I will take up the instrumental challenge, making a list of subjects that I think will be _useful_ in helping graduates become successful in the world of the twenty-first century. In no way do I mean to suggest that students can not be successful if they don't follow this plan for, like Mankiw, I agree that students should ignore advice as they see fit. Education is about discovery as much as anything and there is much to one's education that transcends instrumentality---going to college is not simply about preparing people to enter "the modern economy," even if it is a very-nearly necessary predicate for success in it.

**People should probably know something about economics.** Fair enough. However, I'm not convinced that what most undergraduate students are taught in their introductory economics classes is the most useful thing to learn. Contemporary economics is taught as an axiomatic discipline. That is, a few foundational axioms (i.e., a set of primitive assumptions that are not proved but considered self-evident and necessary) are presented and from these, theorems can be derived. Theorems can then be logically proven by recourse to axioms or other already-proven theorems. Note that this is not about explaining the world around us. It is really an exercise in rigorously defining normative rules for how people _should_ behave and what the consequences of such behavior would be, even if actual people don't follow such prescriptions. Professor Mankiw has written a widely used textbook in introductory economics. In the first chapter of this book, we see this axiomatic approach on full display. We are told not unreasonable things like "People Face Trade-Offs" or "The Cost of Something is What You Give Up to Get It" or "Rational People Think at the Margin." I couldn't agree more with the idea that people face trade-offs, but I nonetheless think there's lot that's problematic here. Consider the following paragraph (p. 5)

> Another trade-off society faces is between efficiency and equality. Efficiency means that society is getting the maximum benefits from its scarce resources. Equality means that those benefits are distributed uniformly among society’s members. In other words, efficiency refers to the size of the economic pie, and equality refers to how the pie is divided into individual slices.

Terms like "efficiency" and "maximum benefits" are presented as unproblematic, as is the idea that there is a necessary trade-off between efficiency and equality. Because it is presented as an axiom (or perhaps it is one of those axiom-like *stylized facts*, with which economists seem to be so enamored), apparently contemporary economic theory allows no possibility for equality in efficient systems. Inequality is naturalized and thereby legitimized. It seems to me that this should be an empirical question, not an axiom. In his masterful book, _The Bounds of Reason: Game Theory and the Unification of the Behavioral Sciences_, Herb Gintis provided a very interesting discussion of the differences between two highly formalized (i.e., mathematical) disciplines, physics and economics. Gintis noted, "By contrast [to the graduate text in quantum mechanics], the microeconomics text, despite its beauty, did not contain a single fact in the whole thousand page volume. Rather, the authors build economic theory in axiomatic fashion, making assumptions on the basis of their intuitive plausibility, their incorporation of the 'stylized facts' of everyday life, or their appeal to the principles of rational thought."

As a post-2010 aside, I will note that the newer [CORE Econ](https://www.core-econ.org/) has done a remarkable job transforming economics education, with a much greater focus on topics like inequality, social responsibility, and sustainability.

If one is going to learn economics, "the study of how society manages its scarce resources"--- and I do believe people should---I think one should (1) learn about how resources are actually managed by real people and real institutions and (2) learn some theory that focuses on strategic interaction. A strategic interaction occurs when the best choice a person can make depends upon what others are doing (and vice-versa). The formal analysis of strategic interactions is done with game theory, a field typically taught in economics classes but also found in political science, biology, and, yes, even anthropology. Alas, this is generally considered an advanced topic, so you'll have to go through all the axiomatic nonsense to get to the really interesting stuff.

OK, that was a bit longer than I anticipated. Whew. On to the other things to learn...

**Learn something about sociology.** Everyone could benefit by understanding how social structures, power relations, and human stocks and flows shape the socially possible. Understanding that social structure and power asymmetries constrain (or enable) what we can do, and even what we can think, is powerful and lets us ask important questions not only about our society but of those of the people with whom we sign international treaties, or engage in trade, or wage war. Some of the critical questions that sociology helps us ask include: who benefits by making inequality axiomatic? Does the best qualified person always get the job? Is teen pregnancy necessarily irrational? Do your economic prospects depend on how many people were born the same year you were? How does taste reflect on one's position in society?

**People should definitely learn some statistics.** Here, Professor Mankiw and I are in complete agreement. I just wish we did a better job teaching introductory statistics. 

**Learn about people other than those just like you.** The fact that we live in a global world is the trite fodder of welcome-to-college speeches by presidents, deans, and other dignitaries. Of course, just because it's trite doesn't make it any less true, and despite the best efforts of homogenizing American popular and consumer culture, not everyone thinks or speaks like us or has the same customs or same religion or system of laws or healing or politics. I know; it's strange. One might learn about other people in an anthropology class, say, but there are certainly other options. If anthropology is the chosen route, I would recommend that one choose carefully, making certain that the readings for any candidate anthropology class be made up of ethnographies and not books on continental philosophy. Come to grips with some of the spectacular diversity that characterizes our species. Even better, spend time living abroad somewhere that pushes you out of your cultural and linguistic comfort zone. You will be better prepared to live in the world of the twenty-first century.

**Take a biology class.** If the twentieth century was the century of physics, the twenty-first century is the century of biology. We have already witnessed a revolution in molecular biology that began around the middle of the twentieth century and continued to accelerate throughout its last decades and into the twenty-first. Genetics has crept into lots of things our parents would not have even imagined: criminology, law, ethics. Our decisions about our own health and that of our loved ones' will increasingly be informed by molecular genetic information. Moreover, the snake-oil salespeople will proliferate (sometimes with the aid of, say, the Secretary of Health and Human Services). People should probably know a thing or two about DNA. I shudder at popular representations of forensic science and worry about a society that believes what it sees on CSI somehow represents reality. Increasingly---as I witness the most astounding dumbassery in public discourse around testosterone, cortisol, and other steroid hormones---I feel like people need to take a physiology class too. I happen to think that when one takes biology, one should also learn something about organisms, but that's gotten harder in many biology departments.

**Finally, learn to write.** Talk about comparative advantage! I am continually blown away by poor preparation that even elite students receive in written English. If you can express ideas in writing clearly and engagingly, you have a skill that will carry you far. Write as much as you possibly can. Learn to edit. I think editing is half the problem with elite students -- they write things at the last minute and expect them to be brilliant. Doesn't work that way. Writing is hard work and well written texts are always well edited.

That was where my list ended in 2010. The intervening 16 years compel me to add another class that every college student should take. As our lives are increasing impacted by climate change, **every college student should take a class on this subject.** Climate change will affect everything about the world college graduates are entering. As Margaret Atwood astutely [noted](https://medium.com/matter/it-s-not-climate-change-it-s-everything-change-8fd9aa671804), it's not climate change; it's everything change. It would be a good idea to acquaint yourself with this reality.

You know what, while I'm at it, I'm just going to recommend one more. **Take a class where you have to read and analyze long-form fiction.** Presumably, this would be in English or some related Literature department. There are so many benefits that come from reading fiction but we're losing our capacity to reap these benefits because everyone is reading less. 

Reading fiction---particularly literary fiction---makes you socially smarter and generally increases your soft skills. When a story engages a reader, it can have durable impacts on their [theory of mind](https://earth.stanford.edu/news/stranger-fiction-climate-storytelling). Read books and you will probably be better at understanding other people. You'll empathize with them and are better able to see the world from their perspective. This is an essential skill for use with both our allies, but also our adversaries. A [very interesting analysis in todays NYTimes](https://www.nytimes.com/2026/06/14/world/europe/us-iran-russia-ukraine.html?unlocked_article_code=1.qFA.pKfD.cPku0MOQK8bk&smid=url-share) suggesting the both the United States and Russia have gotten themselves into deadlocked conflicts because they misread their adversaries, instead projecting their own views onto Iran and Ukraine respectively. Reading fiction and doing the analytic work of a literature class helps you to think about alternative possible worlds. This is an essential task for sustainability, but also for anyone who cares about the future. Learn to think more creatively and with greater empathy and maybe you'll even learn to thrive in the age of LLM slop.

There are, of course, many other classes that more students should take, but in the interest of brevity (too late!), I will stop here. Best of luck to all graduates!